---
title: "Untitled"
author: "Aymeric Stamm"
date: "9/20/2021"
output: html_document
---

```{r setup, include=FALSE}
library(reticulate)
conda_create("r-reticulate", python_version = "3.9")
conda_install("scipy", envname = "r-reticulate")
conda_install("numba", envname = "r-reticulate")
conda_install("triarray", envname = "r-reticulate", pip = TRUE)
conda_install("../", envname = "r-reticulate", pip = TRUE)
old_py <- Sys.getenv("RETICULATE_PYTHON")
Sys.unsetenv("RETICULATE_PYTHON")
use_condaenv("r-reticulate")
```

```{r py-config}
py_config()
```

```{python}
import numpy as np
import flippy
from scipy.stats import norm
from triarray import TriMatrix
```

```{python}
flippy.phipson_smyth_pvalue(10, 50, 1000)
```

```{r}
flipr:::phipson_smyth_pvalue(10, 50, 1000)
```

```{python}
data = norm.rvs(0, 1, size = 100)
flippy.stats2pvalue(0, data, 1000)
```

```{r}
flipr:::stats2pvalue(1, py$data, 1000)
```

```{python}
def stat_t(data, indices1, **kwargs):
    n = len(data)
    n1 = len(indices1)
    n2 = n - n1
    indices2 = list(set(range(n)) - set(indices1))
    x1 = [data[i] for i in indices1]
    x2 = [data[i] for i in indices2]
    return np.mean(x1) - np.mean(x2)
def stat_f(data, indices1, **kwargs):
    n = len(data)
    n1 = len(indices1)
    n2 = n - n1
    indices2 = list(set(range(n)) - set(indices1))
    x1 = [data[i] for i in indices1]
    x2 = [data[i] for i in indices2]
    return np.var(x1, ddof = 1) / np.var(x2, ddof = 1)
```

```{r}
stat_t_r <- function(data, indices1, ...) {
  indices2 <- seq_len(length(data))[-indices1]
  x1 <- unlist(data[indices1])
  x2 <- unlist(data[indices2])
  mean(x1) - mean(x2)
}
stat_f_r <- function(data, indices1, ...) {
  indices2 <- seq_len(length(data))[-indices1]
  x1 <- unlist(data[indices1])
  x2 <- unlist(data[indices2])
  var(x1) / var(x2)
}
```

```{python}
B = 100
M = 100
stat_data = list(data) * 2
n = len(stat_data)
n1 = len(list(data))
perm_data = [list(np.random.choice(n, size = n1)) for _ in range(B)]
perm_data.insert(0, list(range(n1)))
perm_data = np.array(perm_data).transpose()
```

```{python}
flippy.run_permutation_scheme(
    formula = "exact", 
    alternative = "two_tail", 
    stats = [stat_t], 
    B = B, 
    perm_data = perm_data, 
    stat_data = stat_data, 
    M = M, 
    combine_with = "tippett"
)
```

```{r}
flipr:::run_permutation_scheme(
  type = "exact", 
  alternative = "two_tail", 
  stats = list(stat_t_r), 
  B = py$B, 
  perm_data = py$perm_data + 1, 
  stat_data = py$stat_data, 
  M = py$M, 
  combine_with = "tippett"
)
```

```{python}
flippy.run_permutation_scheme(
    formula = "exact", 
    alternative = "two_tail", 
    stats = [stat_t, stat_f], 
    B = B, 
    perm_data = perm_data, 
    stat_data = stat_data, 
    M = M, 
    combine_with = "tippett"
)
```

```{r}
flipr:::run_permutation_scheme(
  type = "exact", 
  alternative = "two_tail", 
  stats = list(stat_t_r, stat_f_r), 
  B = py$B, 
  perm_data = py$perm_data + 1, 
  stat_data = py$stat_data, 
  M = py$M, 
  combine_with = "tippett"
)
```

```{python}
flpy = flippy.flipn(4)
```

```{r}
flipr:::flipn(4)
py$flpy
```

```{python}
help(flippy.stat_welch)
```

```{python}
x = list(np.random.rand(10))
y = list(np.random.rand(10))
```

```{python}
flippy.stat_welch(x + y, range(10))
```

```{r}
flipr::stat_welch(c(py$x, py$y), 1:10)
```

```{python}
flippy.stat_student(x + y, range(10))
```

```{r}
flipr::stat_student(c(py$x, py$y), 1:10)
```

```{python}
flippy.stat_fisher(x + y, range(10))
```

```{r}
flipr::stat_fisher(c(py$x, py$y), 1:10)
```

```{r}
X <- mvtnorm::rmvnorm(10, rep(0, 5))
Y <- mvtnorm::rmvnorm(10, rep(0, 5))
D <- dist(rbind(X, Y), upper = TRUE)
Dv <- as.numeric(D)
xv <- purrr::array_tree(X, margin = 1)
yv <- purrr::array_tree(Y, margin = 1)
```

```{python}
D = TriMatrix(np.array(r.D), upper = True, diag_val = 0)
```

```{python}
flippy.stat_hotelling(r.xv + r.yv, range(10))
```

```{r}
flipr::stat_hotelling(c(xv, yv), 1:10)
```

```{python}
flippy.stat_bs(r.xv + r.yv, range(10))
```

```{r}
flipr::stat_bs(c(xv, yv), 1:10)
```

```{python}
flippy.stat_t_ip(D, range(10))
```

```{r}
flipr::stat_t_ip(D, 1:10)
```

```{python}
flippy.stat_f_ip(D, range(10))
```

```{r}
flipr::stat_f_ip(D, 1:10)
```

```{python}
flippy.stat_bg_ip(D, range(10))
```

```{r}
flipr::stat_bg_ip(D, 1:10)
```

```{python}
flippy.stat_energy_ip(D, range(10))
```

```{r}
flipr::stat_energy_ip(D, 1:10)
```

```{python}
flippy.stat_cq_ip(D, range(10))
```

```{r}
flipr::stat_cq_ip(D, 1:10)
```

```{python}
flippy.stat_mod_ip(D, range(10))
```

```{r}
flipr::stat_mod_ip(D, 1:10)
```

```{python}
flippy.stat_dom_ip(D, range(10))
```

```{r}
flipr::stat_dom_ip(D, 1:10)
```

```{r clean}
Sys.setenv(RETICULATE_PYTHON = old_py)
```
